### ISSUE TITLE
Missing Dependencies. 06/26/2022

### ISSUE THREAD

**Issue by eggman121** [memo33/metarules#1]
Hello. I am getting this issue with the metarules and just wondering if there is a workaround for the issue?

[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.github.memo33#scdbpf_2.11;0.1.7: not found
[warn]  :: com.github.memo33#scalaenum_2.11;0.1.4: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::

Thanks

**Comment by memo33** [comment]
The file hosting service shut down a while ago (again), so I have uploaded all the dependencies to Github for a hopefully longer lasting solution. Instead of automatic dependency management, I link to the uploaded files directly for now (see the commit for the URLs). Retrieving the dependencies for this project should work again now.
